"""Custom exceptions (Phase 0)."""
class CalculatorError(Exception): ...
class OperationError(CalculatorError): ...
class ValidationError(CalculatorError): ...
class ConfigError(CalculatorError): ...
class HistoryError(CalculatorError): ...
class PersistenceError(CalculatorError): ...
